# Generated by Django 3.0.7 on 2020-06-11 11:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('stage', models.IntegerField(
                    choices=[(1, 'Stage1'), (2, 'Stage2')])),
                ('type', models.CharField(choices=[
                    (1, 'Stage1'), (2, 'Stage2')], max_length=128)),
                ('max_score',
                 models.DecimalField(decimal_places=2, max_digits=4)),
                ('text', models.TextField()),
                ('options',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.CharField(max_length=128), null=True,
                     size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='students',
                    to='exam_web.AcademyGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('exam_session',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='user_sessions',
                     to='exam_web.ExamSession')),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='exam_sheet',
                    to='exam_web.Student')),
            ],
            options={
                'unique_together': {('id', 'student', 'exam_session')},
            },
        ),
        migrations.CreateModel(
            name='ExamList',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('answer', models.TextField(null=True)),
                ('answered_at', models.DateTimeField(null=True)),
                ('score', models.DecimalField(
                    decimal_places=2, max_digits=4, null=True)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='exam_web.Question')),
                ('session', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='exam_list',
                    to='exam_web.UserSession')),
                ('student',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.DO_NOTHING,
                     related_name='exam_questions',
                     to='exam_web.Student')),
            ],
            options={
                'unique_together': {('student', 'session', 'question')},
            },
        ),
    ]
