# Generated by Django 3.0.7 on 2020-06-13 15:11
import uuid

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('exam_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamList',
            new_name='ExamTicket',
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=128), blank=True,
                null=True, size=None,
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(
                choices=[
                    (
                        'single', 'Single',
                    ), ('multi', 'Multi'), ('open', 'Open'),
                ], max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='students', to='exam_web.AcademyGroup',
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True,
                serialize=False,
            ),
        ),
    ]
