# Generated by Django 3.0.7 on 2020-06-13 17:22

from django.db import migrations, models
import exam_web.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('exam_web', '0002_auto_20200613_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='token',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.CharField(
                default=exam_web.models.uuid_str, editable=False,
                max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examticket',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examticket',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examticket',
            name='score',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
